// Service worker of the Notfunk-Meldebuch. The logic is shared with the
// other offline tools (../shared/js/sw-core.js); precache.js is generated by
// scripts/build_notfunk.py and defines self.NOTFUNK_PRECACHE.
self.OE1EBG_SW = { prefix: 'notfunk', precache: 'NOTFUNK_PRECACHE' };
importScripts('../shared/js/sw-core.js');
