// Service worker of the Notfunk-Meldebuch. The logic is shared with the
// other offline tools (../shared/js/sw-core.js); precache.js is generated by
// scripts/build_notfunk.py and defines self.NOTFUNK_PRECACHE.
// Cache prefix tools-notfunk: the old install from before /tools/ (caches
// notfunk-<hash>, ../shared/js/sw-move.js) keeps its offline copy until the
// user removes it.
self.OE1EBG_SW = { prefix: 'tools-notfunk', precache: 'NOTFUNK_PRECACHE' };
importScripts('../shared/js/sw-core.js');
