// Service worker of the confirmation log. The logic is shared with the other
// offline tools (../shared/js/sw-core.js); precache.js is generated by
// scripts/build_confirm.py and defines self.CONFIRM_PRECACHE.
// Cache prefix tools-confirm: the old install from before /tools/ (caches
// confirm-<hash>, ../shared/js/sw-move.js) keeps its offline copy until the
// user removes it.
self.OE1EBG_SW = { prefix: 'tools-confirm', precache: 'CONFIRM_PRECACHE' };
importScripts('../shared/js/sw-core.js');
