// Service worker of the confirmation log. The logic is shared with the other
// offline tools (../shared/js/sw-core.js); precache.js is generated by
// scripts/build_confirm.py and defines self.CONFIRM_PRECACHE.
self.OE1EBG_SW = { prefix: 'confirm', precache: 'CONFIRM_PRECACHE' };
importScripts('../shared/js/sw-core.js');
