// "About ADIF compliance & validation" (<details id="compliance"> in
// index.html): what the in-browser check covers, how the editor itself is
// verified, and where this build comes from. The build facts come from
// build-info.js (scripts/build_adif.py): self.ADIF_BUILD = { commit,
// version, run, adifmt, adifChecker, commitFull }; without it (dev server) the panel
// says "development build". Fills itself when imported (app.js).

import { el, fill } from '../../shared/js/dom.js';
import { REPO_URL, commitUrl, extLink } from '../../shared/js/sources.js';
import { ADIF_SPEC_VERSION } from '../../shared/js/adif-spec-data.js';

// "3.1.7" -> the spec page on adif.org.uk
export function adifSpecUrl(version = ADIF_SPEC_VERSION) {
  const v = String(version).replace(/\D/g, '');
  return `https://adif.org.uk/${v}/ADIF_${v}.htm`;
}

// adif-checker is pinned by a Go pseudo-version
// (v0.0.0-20260914171904-aa2fd1bfbb3d): its last part is the commit.
export function goModuleRev(version) {
  const m = /-(\d{14})-([0-9a-f]{12})$/.exec(String(version || ''));
  return m ? { rev: m[2], date: `${m[1].slice(0, 4)}-${m[1].slice(4, 6)}-${m[1].slice(6, 8)}` } : null;
}

// The facts the panel shows, from build-info.js (or nothing in dev): links
// point at the files of the commit the build came from, else at main.
export function complianceFacts(build) {
  const b = build || {};
  const commit = commitUrl(b.commit) ? b.commit : null;
  const ref = commit || 'main';
  const run = /^https:\/\/\S+\/actions\/runs\/(\d+)/.exec(String(b.run || ''));
  return {
    commit,
    commitUrl: commit ? commitUrl(commit) : null,
    // GitHub's checks page needs the full SHA (/commit/<short>/checks is a 404)
    checksUrl: /^[0-9a-f]{40}$/.test(b.commitFull || '') ? `${commitUrl(b.commitFull)}/checks` : null,
    runUrl: run ? b.run : null,
    runId: run ? run[1] : null,
    version: b.version || null,
    adifmt: b.adifmt || null,
    adifChecker: b.adifChecker || null,
    file: path => `${REPO_URL}/blob/${ref}/${path}`,
    workflowUrl: `${REPO_URL}/actions/workflows/ci.yml`,
  };
}

const extIcon = () => el('span', { 'aria-hidden': 'true' }, ' ↗');

function adifmtItem(version) {
  const repo = 'https://github.com/flwyd/adif-multitool';
  return [extLink(repo, 'adifmt'), ' (adif-multitool ',
    version ? extLink(`${repo}/releases/tag/${version}`, version) : 'pinned in tests/tools/go.mod', ')'];
}

function adifCheckerItem(version) {
  const repo = 'https://github.com/k0swe/adif-checker';
  const r = goModuleRev(version);
  return [extLink(repo, 'adif-checker'), ' (',
    r ? ['rev ', extLink(`${repo}/commit/${r.rev}`, r.rev.slice(0, 7)), ` of ${r.date}`]
      : version || 'pinned in tests/tools/go.mod', ')'].flat(); // el() flattens one level only
}

function provenance(f) {
  if (!f.commit) {
    return el('p', null, 'Development build: no build information (build-info.js is generated by ',
      el('code', null, 'just build-adif'), '). ', extLink(f.workflowUrl, 'CI runs'), extIcon(), '.');
  }
  return el('ul', null,
    el('li', null, 'Commit ', extLink(f.commitUrl, f.commit), extIcon(),
      f.checksUrl ? [' · ', extLink(f.checksUrl, 'checks for this commit'), extIcon()] : null),
    el('li', null,
      f.runUrl ? ['Built by ', extLink(f.runUrl, `GitHub Actions run ${f.runId}`), extIcon()] : 'Local build (not built by CI)',
      f.version ? ` · content ${f.version}` : null),
    el('li', null, 'All CI runs: ', extLink(f.workflowUrl, 'workflow “CI”'), extIcon()));
}

export function renderCompliance(root, build) {
  const f = complianceFacts(build);
  const v = ADIF_SPEC_VERSION;
  return fill(root,
    el('h2', null, 'What the check covers'),
    el('p', null, 'Every loaded file is checked in your browser against ',
      extLink(adifSpecUrl(v), `ADIF ${v}`), extIcon(),
      ': syntax (tags, declared lengths, header, records, characters), data types, enumerations and ranges ',
      '(generated from the specification’s own machine-readable exports), and cross-field checks ',
      '(band vs. frequency, mode vs. submode, locator extensions, …). After the first edit the log is ',
      're-checked as the .adi export would write it.'),
    el('ul', null,
      el('li', null, el('span', { class: 'sev-error' }, 'error'), ': syntax or specification violation; the file is not valid ADIF.'),
      el('li', null, el('span', { class: 'sev-warning' }, 'warning'), ': valid, but inconsistent or suspicious.'),
      el('li', null, el('span', { class: 'sev-info' }, 'info'), ': interoperability hint.')),
    el('p', null, 'Valid means: no error. Warnings and infos never make a file invalid.'),

    el('h2', null, 'How this editor is verified'),
    el('ul', null,
      el('li', null, 'The ', extLink(f.file('tests/adif-official.test.mjs'), 'official ADIF test QSOs'), extIcon(),
        ' (every field and enumeration value) pass the validator without a single issue, and the editor’s export of them has no error.'),
      el('li', null, 'The .adi export is tested with a ', extLink(f.file('tests/adif-spec.mjs'), 'strict, independent reader'), extIcon(), '.'),
      el('li', null, 'Cross-checked against ', adifmtItem(f.adifmt), ' and ', adifCheckerItem(f.adifChecker),
        ' on every change to ADIF code, on every release and weekly; a release whose cross-checks fail is not published.'),
      el('li', null, 'Where those tools disagree, the case is looked up in the specification: ',
        extLink(`${f.file('tools/adif/README.md')}#cross-checks-with-other-tools`, 'known differences'), extIcon(), '.')),

    el('h2', null, 'This build'),
    provenance(f));
}

const complianceRoot = typeof document !== 'undefined' && document.getElementById('compliance-body');
if (complianceRoot) renderCompliance(complianceRoot, globalThis.ADIF_BUILD);
