// Export formats of the ADIF editor: ADI, plain CSV and the SOTA database's
// V2 CSV. Pure functions over (records, columns) — no DOM — so they're
// unit-tested in oe1ebg/tests/.

import { adifAscii, adifAsciiField } from '../../shared/js/adif.js';
import { ADIF_SPEC_FIELDS } from '../../shared/js/adif-spec-data.js';

// No registered MIME type for ADIF; text/plain makes Safari save ".adi.txt".
export const ADI_MIME = 'application/octet-stream';

// Values may keep < and > (legal inside a length-delimited value), and
// MultilineString fields (ADDRESS, NOTES, ...) their line breaks. So may
// application-defined fields: they are written without a type indicator,
// which ADIF reads as MultilineString.
const ASCII_OPTS = { keepBrackets: true };
const MULTILINE_OPTS = { keepBrackets: true, multiline: true };
const asciiOpts = col => ADIF_SPEC_FIELDS[col]?.type === 'MultilineString' || col.startsWith('APP_') ? MULTILINE_OPTS : ASCII_OPTS;

// ADI is an ASCII format (ADIF 3.1.7: String = ASCII 32-126, the length
// counts characters): values are transliterated like in the confirmation
// log's export (adifAscii in shared/js/adif.js).
export function serializeADIF(records, columns, createdIso = new Date().toISOString()){
  const ts = createdIso.replace(/[-:]/g, '').replace('T', ' ').slice(0, 15);
  let out = "Generated by ADIF Editor (client-side, no server round-trip)\n";
  out += `<PROGRAMID:10>ADIFEditor\n<ADIF_VER:5>3.1.7\n<CREATED_TIMESTAMP:15>${ts}\n<EOH>\n\n`;
  for (const rec of records){
    let line = "";
    for (const col of columns) line += adifAsciiField(col, rec[col], asciiOpts(col)); // skips empty values
    out += line + "<EOR>\n";
  }
  return out;
}

// How many values the ADI export has to change (non-ASCII characters,
// line breaks, surrounding blanks), so the editor can say so.
export function adifChangedValues(records, columns){
  let n = 0;
  for (const rec of records) for (const col of columns) {
    const v = rec[col];
    if (v !== undefined && v !== null && v !== '' && adifAscii(v, asciiOpts(col)) !== String(v)) n++;
  }
  return n;
}

function csvEscapeRFC4180(val){
  const s = (val === undefined || val === null) ? '' : String(val);
  return /[",\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
}

export function serializeCSV(records, columns){
  // Unlike serializeADIF, every column must be emitted positionally (including
  // blank cells) or rows would misalign — don't reuse the ADIF skip-empty loop.
  const lines = [columns.map(csvEscapeRFC4180).join(',')];
  for (const rec of records){
    lines.push(columns.map(c => csvEscapeRFC4180(rec[c] ?? '')).join(','));
  }
  // BOM: Excel only reads the file as UTF-8 (umlauts) with it. Not for the
  // SOTA CSV below, whose importer expects plain text.
  return '\ufeff' + lines.join('\r\n');
}

/* SOTA database V2 CSV format, verified against sotadata.org.uk's own
   ActivatorCSVInfo.htm and a working converter's source (not just blog posts):
   V2,<My Callsign>,<My Summit>,<Date DD/MM/YYYY>,<Time HHMM>,<Band>,<Mode>,
   <His Callsign>,<His Summit>,<Notes/Comments> */

function sotaSanitizeField(val){
  // SOTA's CSV importer has no quoting support: commas must not appear in any
  // field. Deliberately NOT sharing csvEscapeRFC4180 with this exporter.
  return (val || '').replace(/,/g, ';');
}

function sotaDate(qsoDate){
  return /^\d{8}$/.test(qsoDate || '') ? `${qsoDate.slice(6,8)}/${qsoDate.slice(4,6)}/${qsoDate.slice(0,4)}` : '';
}

function sotaTime(timeOn){
  const t = timeOn || '';
  return t.length >= 4 ? t.slice(0,4) : '';
}

function sotaRow(rec){
  const myCall = rec.STATION_CALLSIGN || rec.OPERATOR || '';
  return [
    'V2', myCall, rec.MY_SOTA_REF || '', sotaDate(rec.QSO_DATE), sotaTime(rec.TIME_ON),
    rec.BAND || '', rec.MODE || '', rec.CALL || '', rec.SOTA_REF || '',
    rec.COMMENT || rec.NOTES || ''
  ].map(sotaSanitizeField).join(',');
}

export function serializeSotaCsv(records, mode){
  const field = mode === 'chaser' ? 'SOTA_REF' : 'MY_SOTA_REF';
  const filtered = records.filter(r => (r[field] || '').trim() !== '');
  // SOTA requires chronological order; sort only this exported copy, never
  // the main table's row order.
  filtered.sort((a, b) => (a.QSO_DATE + a.TIME_ON).localeCompare(b.QSO_DATE + b.TIME_ON));
  return filtered.length ? filtered.map(sotaRow).join('\r\n') + '\r\n' : '';
}
