from __future__ import annotations

import hashlib
import re
from pathlib import Path

from offline_tool import BUILD_INFO_NAME, build_info_js, build_run, git_commit, git_commit_full
from single_file import bundle_modules, inline_vendor, script_safe

# Build step for the ADIF editor (oe1ebg/tools/adif/). Writes two
# git-ignored files, before scripts/build_site.py copies them into the bundle:
#
# 1. adif-editor.html: the whole editor in ONE file (js/ modules and the
#    tools/shared/ modules they import, inlined by scripts/single_file.py),
#    so it can be saved and opened via file://, where module scripts don't
#    load. The published adif/ page itself loads the ES modules.
#
# 2. build-info.js: `self.ADIF_BUILD = { commit, version, run, adifmt,
#    adifChecker }` for the "About ADIF compliance & validation" panel
#    (js/compliance.js): the commit (GIT_SHA, as for the offline tools), a
#    content hash of the bundle, the CI run that built it (BUILD_RUN_URL,
#    null for a local build) and the versions of the cross-check tools
#    pinned in tests/tools/go.mod. adif-editor.html gets the same object
#    inlined. Without it (dev server) the panel says "dev build".
#
# Stdlib only.

OE1EBG_DIR = Path(__file__).resolve().parent.parent
ADIF_DIR = OE1EBG_DIR / "tools" / "adif"
GO_MOD = OE1EBG_DIR / "tests" / "tools" / "go.mod"
BUNDLE_NAME = "adif-editor.html"
SCRIPT_BLOCK_RE = re.compile(r"<!-- ADIF-SCRIPT-BEGIN -->.*?<!-- ADIF-SCRIPT-END -->", re.S)
# theme script and stylesheets (tools/shared/ + the tool's style.css), inlined
VENDOR_BLOCK_RE = re.compile(r"<!-- ADIF-VENDOR-BEGIN -->(.*?)<!-- ADIF-VENDOR-END -->", re.S)
# The cross-check tools (tests/adif-crosscheck.test.mjs) and their keys in build-info.js.
CROSSCHECK_MODULES = {"adifmt": "github.com/flwyd/adif-multitool", "adifChecker": "github.com/k0swe/adif-checker"}


def crosscheck_versions() -> dict[str, str | None]:
    """Module versions of the cross-check tools from go.mod's require block
    (adifmt: v0.1.22; adif-checker: a pseudo-version ending in the commit)."""
    text = GO_MOD.read_text(encoding="utf-8") if GO_MOD.exists() else ""
    out = {}
    for key, module in CROSSCHECK_MODULES.items():
        m = re.search(rf"^\s*{re.escape(module)}\s+(v\S+)", text, re.M)
        out[key] = m.group(1) if m else None
    return out


def build_bundle(info_js: str = "") -> str:
    html = (ADIF_DIR / "index.html").read_text(encoding="utf-8")
    # build-info.js (part of the SCRIPT block) inlined before the app.
    js = script_safe(info_js + bundle_modules(ADIF_DIR / "js" / "app.js"))
    html, n = SCRIPT_BLOCK_RE.subn(lambda _m: f"<script>\n{js}</script>", html)
    if n != 1:
        raise SystemExit("index.html: ADIF-SCRIPT markers not found")
    html, n = VENDOR_BLOCK_RE.subn(lambda m: inline_vendor(m.group(1), ADIF_DIR), html)
    if n != 1:
        raise SystemExit("index.html: ADIF-VENDOR markers not found")
    return html


def main() -> None:
    # The version hashes the bundle without build info, so it changes only
    # with the shipped content (not with every commit).
    version = hashlib.sha256(build_bundle().encode()).hexdigest()[:12]
    info = {"commit": git_commit(), "version": version, "run": build_run(), **crosscheck_versions(),
            "commitFull": git_commit_full()}
    info_js = build_info_js("ADIF", info)
    (ADIF_DIR / BUILD_INFO_NAME).write_text("// Generated by scripts/build_adif.py — do not edit.\n" + info_js, encoding="utf-8")
    html = build_bundle(info_js)
    (ADIF_DIR / BUNDLE_NAME).write_text(html, encoding="utf-8")
    run = info["run"] or "local build"
    print(f"adif: commit {info['commit']}, version {version}, {run}; wrote {BUILD_INFO_NAME}, {BUNDLE_NAME} ({len(html.encode()) / 1024:.0f} KiB)")


if __name__ == "__main__":
    main()
