from __future__ import annotations

import base64
import hashlib
import re
from pathlib import Path

# Build step for the offline confirmation log (oe1ebg/docs/confirm/). Runs
# before `zensical build`, which then copies the generated files into site/.
# Stdlib only. Produces two git-ignored files:
#
# 1. confirm-offline.html — the whole tool in ONE file (all js/ modules and,
#    once they exist, all data/ files inlined). Copy it to a USB stick or
#    laptop and open it via file://, where neither service workers nor ES
#    module scripts work. Modules are "bundled" by plain concatenation in
#    dependency order with import lines and `export` keywords stripped,
#    wrapped in one IIFE — so js/ modules must keep their top-level names
#    unique and use only single-statement `import {...} from './x.js';`.
#
# 2. precache.js — the service worker's file list plus a content-hash
#    version (see docs/confirm/sw.js). Any change to any shipped file
#    changes the version, which makes browsers install the new version in
#    the background (activated only when the user clicks "Update").

OE1EBG_DIR = Path(__file__).resolve().parent.parent
CONFIRM_DIR = OE1EBG_DIR / "docs" / "confirm"
BUNDLE_NAME = "confirm-offline.html"
PRECACHE_NAME = "precache.js"

# Not shipped to / cached by the browser.
EXCLUDE = {"sw.js", PRECACHE_NAME, "AGENTS.md"}

IMPORT_RE = re.compile(r"^import\s*\{[^}]*\}\s*from\s*['\"](\./[^'\"]+)['\"];?[ \t]*\n", re.M)
EXPORT_RE = re.compile(r"^export\s+(?=(async\s+)?(function|const|let|class)\b)", re.M)
SCRIPT_BLOCK_RE = re.compile(r"<!-- CONFIRM-SCRIPT-BEGIN -->.*?<!-- CONFIRM-SCRIPT-END -->", re.S)


def module_order(entry: Path) -> list[Path]:
    order: list[Path] = []
    seen: set[Path] = set()

    def visit(path: Path) -> None:
        if path in seen:
            return
        seen.add(path)
        for dep in IMPORT_RE.findall(path.read_text(encoding="utf-8")):
            visit((path.parent / dep).resolve())
        order.append(path)

    visit(entry.resolve())
    return order


def bundle_js() -> str:
    parts = []
    for path in module_order(CONFIRM_DIR / "js" / "app.js"):
        src = path.read_text(encoding="utf-8")
        src = IMPORT_RE.sub("", src)
        src = EXPORT_RE.sub("", src)
        if re.search(r"^\s*(import|export)\b", src, re.M):
            raise SystemExit(f"{path.name}: unsupported import/export form for the offline bundle")
        parts.append(f"// ---- {path.relative_to(CONFIRM_DIR)} ----\n{src}")
    return "(() => {\n'use strict';\n" + "\n".join(parts) + "\n})();\n"


def build_bundle() -> str:
    html = (CONFIRM_DIR / "index.html").read_text(encoding="utf-8")
    js = bundle_js().replace("</script", "<\\/script")
    html, n = SCRIPT_BLOCK_RE.subn(lambda _m: f"<script>\n{js}</script>", html)
    if n != 1:
        raise SystemExit("index.html: CONFIRM-SCRIPT markers not found")
    # No manifest (meaningless on file://); icon inlined so the file is self-contained.
    html = re.sub(r'\s*<link rel="manifest"[^>]*>', "", html)
    icon = base64.b64encode((CONFIRM_DIR / "icon.svg").read_bytes()).decode()
    html = html.replace('href="icon.svg"', f'href="data:image/svg+xml;base64,{icon}"')
    return html


def shipped_files() -> list[Path]:
    files = []
    for p in sorted(CONFIRM_DIR.rglob("*")):
        if p.is_file() and p.name not in EXCLUDE and not p.name.startswith("."):
            files.append(p)
    return files


def main() -> None:
    bundle_path = CONFIRM_DIR / BUNDLE_NAME
    bundle_path.write_text(build_bundle(), encoding="utf-8")

    files = shipped_files()
    h = hashlib.sha256()
    for p in files:
        h.update(p.relative_to(CONFIRM_DIR).as_posix().encode())
        h.update(b"\0")
        h.update(p.read_bytes())
    version = h.hexdigest()[:12]

    entries = ["./"] + [p.relative_to(CONFIRM_DIR).as_posix() for p in files]
    listing = ",\n".join(f"    {e!r}" for e in entries).replace("'", '"')
    (CONFIRM_DIR / PRECACHE_NAME).write_text(
        "// Generated by scripts/build_confirm.py — do not edit.\n"
        f'self.CONFIRM_PRECACHE = {{\n  version: "{version}",\n  files: [\n{listing},\n  ],\n}};\n',
        encoding="utf-8",
    )
    total = sum(p.stat().st_size for p in files)
    print(f"confirm: version {version}, {len(files)} files, {total / 1024:.0f} KiB precached; wrote {BUNDLE_NAME}")


if __name__ == "__main__":
    main()
